package codigo;


import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author http://www.chuidiang.org/java/mysql/resultset_jtable.php
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    
    /**
     * Mete el modelo que recibe en la tabla.
     * @param modelo
     */
   
    String cadena_error = "";
    DefaultTableModel modelo;
    
    public Formulario() {
        initComponents();    
        
        try {
            gc.conn1.setAutoCommit(false);
            
            Statement sta = gc.conn1.createStatement();
            
            String query = "SELECT * FROM album ";
            
            ResultSet rs = sta.executeQuery(query);           
            ResultSetMetaData metaDatos = rs.getMetaData();
            
            int numColumnas = metaDatos.getColumnCount();
            
            modelo = new DefaultTableModel();
            
            this.tabla.setModel(modelo);
            
            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }
            
            while (rs.next()) {                
                Object[] fila = new Object[numColumnas];
                
                for (int i = 0; i < numColumnas; i++) {
                    fila [i] = rs.getObject(i +1);
                }
                modelo.addRow(fila);
            }
            
            rs.close();
            
            sta.close();
        } catch (Exception e) {
            e.printStackTrace();
            cadena_error = e.toString();
            errores.setText(cadena_error);
        }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AñadirColumna = new javax.swing.JButton();
        nombreColumna = new javax.swing.JTextField();
        ConsultaCancion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        InsertarAlbum = new javax.swing.JButton();
        ConsultaAlbum = new javax.swing.JButton();
        ConsultaPorId = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        InsertarCancion = new javax.swing.JButton();
        IdNewAlbum = new javax.swing.JTextField();
        IdNewCancion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Año = new javax.swing.JTextField();
        Titulo = new javax.swing.JTextField();
        Duracion = new javax.swing.JTextField();
        Letra = new javax.swing.JTextField();
        Id_AlbumNewCancion = new javax.swing.JTextField();
        errores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AñadirColumna.setText("Añadir columna");
        AñadirColumna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AñadirColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirColumnaActionPerformed(evt);
            }
        });

        nombreColumna.setEditable(false);
        nombreColumna.setText("Imagen Album");
        nombreColumna.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ConsultaCancion.setText("consultar tabla cancion");
        ConsultaCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultaCancion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConsultaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaCancionActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setEnabled(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        InsertarAlbum.setText("Insertar nuevo album");
        InsertarAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarAlbumActionPerformed(evt);
            }
        });

        ConsultaAlbum.setText("consultar tabla album");
        ConsultaAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultaAlbum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConsultaAlbum.setMaximumSize(new java.awt.Dimension(143, 23));
        ConsultaAlbum.setMinimumSize(new java.awt.Dimension(143, 23));
        ConsultaAlbum.setPreferredSize(new java.awt.Dimension(143, 23));
        ConsultaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAlbumActionPerformed(evt);
            }
        });

        ConsultaPorId.setText("Consulta cancion por id:");
        ConsultaPorId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultaPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPorIdActionPerformed(evt);
            }
        });

        Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Id.setText("1");
        Id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdMousePressed(evt);
            }
        });

        InsertarCancion.setText("Insertar nueva cancion");
        InsertarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarCancionActionPerformed(evt);
            }
        });

        IdNewAlbum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdNewAlbum.setText("Id");
        IdNewAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IdNewAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdNewAlbumMousePressed(evt);
            }
        });

        IdNewCancion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdNewCancion.setText("Id");
        IdNewCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IdNewCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdNewCancionMousePressed(evt);
            }
        });

        Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre.setText("Nombre");
        Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreMousePressed(evt);
            }
        });

        Año.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Año.setText("Año");
        Año.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Año.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AñoMousePressed(evt);
            }
        });

        Titulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Titulo.setText("Titulo");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TituloMousePressed(evt);
            }
        });

        Duracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Duracion.setText("Duracion");
        Duracion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Duracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DuracionMousePressed(evt);
            }
        });

        Letra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Letra.setText("Letra");
        Letra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Letra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LetraMousePressed(evt);
            }
        });

        Id_AlbumNewCancion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Id_AlbumNewCancion.setText("Id_Album");
        Id_AlbumNewCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Id_AlbumNewCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Id_AlbumNewCancionMousePressed(evt);
            }
        });

        errores.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(InsertarCancion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InsertarAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConsultaPorId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombreColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AñadirColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(IdNewCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Letra, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Id_AlbumNewCancion))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(IdNewAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ConsultaAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ConsultaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addGap(296, 296, 296)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreColumna, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConsultaPorId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Id)
                    .addComponent(AñadirColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaCancion)
                    .addComponent(ConsultaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarAlbum)
                    .addComponent(IdNewAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarCancion)
                    .addComponent(IdNewCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Id_AlbumNewCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errores, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAlbumActionPerformed
        try {
            gc.conn1.setAutoCommit(false);

            String query = "SELECT * FROM album ";

            Statement sta = gc.conn1.createStatement();

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

             modelo = new DefaultTableModel();

            this.tabla.setModel(modelo);

            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object [] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila [i] = rs.getObject(i +1);
                }
                modelo.addRow(fila);
            }
            
            rs.close();

            sta.close();
        } catch (Exception e) {
            e.printStackTrace();
            cadena_error = e.toString();
            errores.setText(cadena_error);
        }
    }//GEN-LAST:event_ConsultaAlbumActionPerformed

    private void InsertarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarAlbumActionPerformed
        gc.insertarDatosAlbum(IdNewAlbum.getText(), Nombre.getText(), Año.getText());
        
        ConsultaAlbumActionPerformed(evt);
        
        
            errores.setText(gc.cadena_error);
    }//GEN-LAST:event_InsertarAlbumActionPerformed

    private void ConsultaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCancionActionPerformed
        try {
            gc.conn1.setAutoCommit(false);

            String query = "SELECT * FROM cancion ";

            Statement sta = gc.conn1.createStatement();

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            modelo = new DefaultTableModel();

            this.tabla.setModel(modelo);

            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object [] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila [i] = rs.getObject(i +1);
                }
                modelo.addRow(fila);
            }

            rs.close();

            sta.close();
        } catch (Exception e) {
            e.printStackTrace();
            cadena_error = e.toString();
            errores.setText(cadena_error);
        }
    }//GEN-LAST:event_ConsultaCancionActionPerformed

    private void AñadirColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirColumnaActionPerformed
        gc.addColumna(nombreColumna.getText());
        
        
            errores.setText(gc.cadena_error);
    }//GEN-LAST:event_AñadirColumnaActionPerformed

    private void ConsultaPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPorIdActionPerformed
                try {
                gc.conn1.setAutoCommit(false);
                
                String ID = Id.getText();
                //con la interrogacion salta un fallo por mi forma de crear la tabla o al menos eso es lo q creo


//                String query = "SELECT * FROM cancion WHERE Id like ? ";
                String query = "SELECT * FROM cancion WHERE Id like "+ ID;
                Statement sta = gc.conn1.createStatement();
                
//                PreparedStatement pst = gc.conn1.prepareStatement(query);
                
//                pst.setString(1, ID);
                
                ResultSet rs = sta.executeQuery(query);
                
                ResultSetMetaData metaDatos = rs.getMetaData();

                int numColumnas = metaDatos.getColumnCount();

                modelo = new DefaultTableModel();

                this.tabla.setModel(modelo);

                for (int i = 1; i <= numColumnas; i++) {
                    modelo.addColumn(metaDatos.getColumnLabel(i));
                }

                while (rs.next()) {
                    Object [] fila = new Object[numColumnas];

                    for (int i = 0; i < numColumnas; i++) {
                        fila [i] = rs.getObject(i +1);
                    }
                    modelo.addRow(fila);
                }

                rs.close();

                sta.close();
                
                System.out.println("Consultado correctamente");
                
//                pst.close();

            } catch (Exception e) {
                e.printStackTrace();
                cadena_error = e.toString();
                errores.setText(cadena_error);
            }
    }//GEN-LAST:event_ConsultaPorIdActionPerformed

    private void IdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdMousePressed
        Id.setText("");
    }//GEN-LAST:event_IdMousePressed

    private void InsertarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarCancionActionPerformed
        gc.insertarDatosCancion(IdNewCancion.getText(), Titulo.getText(), Duracion.getText(), Letra.getText(), Id_AlbumNewCancion.getText());
        
        ConsultaCancionActionPerformed(evt);
        
        
            errores.setText(gc.cadena_error);
    }//GEN-LAST:event_InsertarCancionActionPerformed

    private void Id_AlbumNewCancionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Id_AlbumNewCancionMousePressed
        Id_AlbumNewCancion.setText("");
    }//GEN-LAST:event_Id_AlbumNewCancionMousePressed

    private void LetraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LetraMousePressed
        Letra.setText("");
    }//GEN-LAST:event_LetraMousePressed

    private void DuracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DuracionMousePressed
        Duracion.setText("");
    }//GEN-LAST:event_DuracionMousePressed

    private void TituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMousePressed
        Titulo.setText("");
    }//GEN-LAST:event_TituloMousePressed

    private void IdNewCancionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdNewCancionMousePressed
        IdNewCancion.setText("");
    }//GEN-LAST:event_IdNewCancionMousePressed

    private void IdNewAlbumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdNewAlbumMousePressed
        IdNewAlbum.setText("");
    }//GEN-LAST:event_IdNewAlbumMousePressed

    private void NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreMousePressed
        Nombre.setText("");
    }//GEN-LAST:event_NombreMousePressed

    private void AñoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñoMousePressed
        Año.setText("");
    }//GEN-LAST:event_AñoMousePressed

    /**
     * @param args the command line arguments
     */
    
    GestorConexion gc = new GestorConexion();
    



    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirColumna;
    private javax.swing.JTextField Año;
    private javax.swing.JButton ConsultaAlbum;
    private javax.swing.JButton ConsultaCancion;
    private javax.swing.JButton ConsultaPorId;
    private javax.swing.JTextField Duracion;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField IdNewAlbum;
    private javax.swing.JTextField IdNewCancion;
    private javax.swing.JTextField Id_AlbumNewCancion;
    private javax.swing.JButton InsertarAlbum;
    private javax.swing.JButton InsertarCancion;
    private javax.swing.JTextField Letra;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel errores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreColumna;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
